server:
  port: 9006
spring:
  application:
    name: tensquare-gathering
  redis:
    host: 192.168.8.128
    port: 6379
    password: lzt4922
  datasource:
    url: jdbc:mysql://192.168.8.128:3306/tensquare_gathering?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lzt4922
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
